# This workflow integrates QwietAI preZero SAST with GitHub and exports SARIF results to the Security Tab
name: QwietAI

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 11 * * 6'

permissions:
  security-events: write  # Ensure proper permissions to upload SARIF results

jobs:
  QwietAI-preZero-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Java JDK v8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8

    - name: Gradle
      run: |
        services/identity/gradlew init

    
    - name: Download QwietAI CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: QwietAI preZero Analysis
      #run: ${GITHUB_WORKSPACE}/sl analyze --strict --wait --verbose --app QWIETAI-crAPI --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }}
      run: ${GITHUB_WORKSPACE}/sl analyze --strict --wait --verbose --app crAPI --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }}
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN_POC }}
